# These are supported funding model platforms

github: [FMCalisto, bruno-oliveira, joaobcampos, echo66]
patreon: oppr
open_collective: oppr
ko_fi: opprGroup
tidelift: #
community_bridge: oppr
liberapay: oppr
issuehunt: opprgroup
otechie: oppr
custom: ['https://paypal.me/oppr']
