# These are supported funding model platforms

github: [FMCalisto, bruno-oliveira, joaobcampos, echo66]
patreon: oppr
open_collective: oppr
ko_fi: opprGroup
tidelift: oppr/medical-image-downloader
community_bridge: oppr
liberapay: oppr
issuehunt: opprgroup
otechie: oppr
custom: ['https://oppr.io', 'https://dev.oppr.io', https://certificates.oppr.io]
