# These are supported funding model platforms

github: [FMCalisto, bruno-oliveira, joaobcampos, echo66]
patreon: oppr
open_collective: oppr
ko_fi: opprGroup
tidelift: #
community_bridge: 67d0a58f-cfd0-40b8-bd08-e13d96304c13
liberapay: oppr
issuehunt: #
otechie: #
custom: ['https://paypal.me/oppr']
